[project]
name = "FLRW-Net"
version = "0.1.0"
description = "FLRW-Net is a neural network that solves the equations of motion in Euclidean Regge calculus."
authors = [
    {name = "Florian Emanuel Hilpert", email = "82518583+Hilpertspace@users.noreply.github.com"},
]

requires-python = ">=3.9,<3.11"

dependencies = [
    # Linux & Windows
    "tensorflow==2.10.1; platform_system != 'Darwin'",

    # macOS (Intel only)
    "tensorflow-macos==2.10.0; platform_system == 'Darwin' and platform_machine == 'x86_64'",

    # Apple Silicon
    "tensorflow-macos==2.10.0; platform_system == 'Darwin' and platform_machine == 'arm64'",
    "tensorflow-metal; platform_system == 'Darwin' and platform_machine == 'arm64'",

    "numpy<2.0",
    "tqdm==4.62.2",
    "matplotlib<3.11,>=3.8"
]

[project.optional-dependencies]
dev = ["ruff>=0.1.0", "pytest>=7.0"]
notebooks = ["ipykernel>=6.0", "notebook>=6.4"]

readme = "README.md"
license = {text = "LICENSE"}

[tool.pdm]
distribution = false

[tool.pdm.scripts]
lint = "ruff check . --fix"
format = "ruff format ."
test = "pytest"
start-flrw-net "python FLRW-Net/src/FLRW_Net.py"

[tool.ruff]
lint.select = ["D", "F", "F841", "I", "Q", "W292", "ANN"]
lint.ignore = ["D107", "D203", "D211", "D213"]
line-length = 120
exclude = [".venv"]

# Per-file ignores (optional)
[tool.ruff.lint.per-file-ignores]
"FLRW-Net/tests/*" = ["D", "ANN"]

[tool.pytest.ini_options]
testpaths = [
  "FLRW-Net/tests"
]
